name: Silverstripe CMS PHPUnit tests
description: Run PHPUnit test for a Siverstripe CMS module

inputs:
  args:
    description: Extra ars to pass to PHP Unit
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Run test suite
      env:
        SS_ENVIRONMENT_TYPE: dev
        SS_DATABASE_CLASS: ${{ env.SS_DATABASE_CLASS }}
        SS_DATABASE_SERVER: ${{ env.SS_DATABASE_SERVER }}
        SS_DATABASE_USERNAME: ${{ env.SS_DATABASE_USERNAME }}
        SS_DATABASE_PASSWORD: ${{ env.SS_DATABASE_PASSWORD }}
        SS_DATABASE_NAME: ${{ env.SS_DATABASE_NAME }}
        SS_SQLITE_DATABASE_PATH: ${{ env.SS_SQLITE_DATABASE_PATH }}
      run: vendor/bin/phpunit ${{ inputs.args }}
      shell: bash
