name: Silverstripe CMS PHPUnit tests
description: Run PHPUnit test for a Siverstripe CMS module
inputs:
  phpVersion:
    description: PHP Version to run the test against
    required: true
    default: 7.4
  databaseDriver:
    description: Which Database to use
    required: true
    default: mysql
  composer-stability:
    description: composer stability flag
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Run test suite
      env:
        DB: MYSQL
        SS_ENVIRONMENT_TYPE: dev
        SS_DATABASE_CLASS: MySQLDatabase
        SS_DATABASE_SERVER: 127.0.0.1
        SS_DATABASE_USERNAME: root
        SS_DATABASE_PASSWORD: root
        SS_DATABASE_NAME: SS_mysite
      run: vendor/bin/phpunit
      shell: bash
