name: Silverstripe CMS PHPUnit tests
description: Run PHPUnit test for a Siverstripe CMS module
inputs:
  phpVersion:
    description: PHP Version to run the test against
    required: true
    default: 7.4
  databaseDriver:
    description: Which Database to use
    required: true
    default: mysql
  composer-stability:
    description: composer stability flag
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Kill local MySQL instance
      run: sudo service mysql stop
      shell: bash
      
    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: 5.7
        mysql root password: root
        
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.phpVersion }}
        extensions: imagick, swoole
        
    
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict
      shell: bash

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
          
    - name: Require test dependencies
      run: composer require silverstripe/recipe-cms=^4 --no-update
      shell: bash

    - name: Install dependencies
      run: composer update --prefer-source --no-progress ${{ inputs.composer-stability }}
      shell: bash

    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping --host=127.0.0.1 --password=root --silent; do
          sleep 1
        done
      shell: bash

    - name: Run test suite
      env:
        DB: MYSQL
        SS_ENVIRONMENT_TYPE: dev
        SS_DATABASE_CLASS: MySQLDatabase
        SS_DATABASE_SERVER: 127.0.0.1
        SS_DATABASE_USERNAME: root
        SS_DATABASE_PASSWORD: root
        SS_DATABASE_NAME: SS_mysite
      run: vendor/bin/phpunit
      shell: bash
